name: Development CI

on:
  push:
    branches: [development, master]
    paths-ignore: ['*.md']

jobs:
  Sast-Development:
    environment: development
    runs-on: ubuntu-latest
    name: SAST Scan

    permissions:
      security-events: write

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@7237412fdd36af517e2745077cedbf9d6900d711
      with:
        args: '. --sarif --output results.sarif || true'

  Build-Development:
    environment: development
    runs-on: ubuntu-latest
    needs: [Sast-Development]
    name: Node ${{ matrix.node-version }} Ubuntu Build

    strategy:
      matrix:
        node-version: [14.17.x, 16.x]

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: Build App
      run: |
        npm install
        npm run build

  Coverage-Tests:
    environment: development
    runs-on: ubuntu-latest
    name: Coverage Tests - Node ${{ matrix.node-version }}
    needs: [Build-Development]

    strategy:
      matrix:
        node-version: [14.17.x, 16.x]

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: Install Dependencies
      run: |
        npm install

    - name: Units Tests
      run: npm run test:unit

    - name: Integration Tests
      run: npm run test:integration

  Jest-Coverage:
    name: test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 14.17.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.17.x

    - name: npm install, make test-coverage
      run: |
        npm install
        npm run test:ci

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
